### ISSUE TITLE
Pretrain dataset

### ISSUE THREAD

**Issue by indiejoseph** [Standard-Intelligence/hertz-dev#1]
Where can I find the detail of the pretraining? eg: languages and hours in the dataset

**Comment by laubonghaudoi** [comment]
I have the same question. How many hours of training data does it use? What's the domain and language distributions of the training data? Is it English-only or it contains other languages as well? Is it all from podcasts and YouTube and does it have audiobook / music as well?

**Comment by ahmedosman2001** [comment]
On this post they claim it was trained on 20 million unique hours of high-quality audio data. Also it seem to be trained 
on multilingual data. If we can get more info, that would be great 

Source: This [post](https://nitter.poast.org/si_pbc/status/1853184307063660723)

**Comment by devanshrpandey** [comment]
Yes, it was trained on 20m hours of general speech data, about 50% English. Most common non-English languages are Spanish and Chinese. The audio data is generally representative of public high-quality audio data.
