### ISSUE TITLE
Questions about bitrate calculation

### ISSUE THREAD

**Issue by sphmel** [Standard-Intelligence/hertz-dev#2]
In blog post, Stage 1 codec has 1kbps bitrate.

```
hertz-codec: a convolutional audio autoencoder that takes mono, 16kHz speech and transforms it into a 8 Hz latent 
representation at about 1kbps bitrate. Stage 1 at 1kbps outperforms Soundstream and Encodec at 6kbps and is on par 
with DAC at 8kbps in subjective evaluations, while having lower tokens per second than any popular tokenizer, critical for 
language modeling. Stage 1 has 5 million encoder parameters and 95 million decoder parameters.
```

How did you calculate this bitrate? It seems audio_tokenizer here 
https://github.com/Standard-Intelligence/hertz-dev/blob/30271b5c9a3bd3c8e972c83e10fdb9d9db2834c8/tokenizer.py#L542

utilizes Gaussian bottleneck , which is common VAE bottle necks. If it has 32 dim dimension bottleneck than each elem has 32bits. so 32 bits/elem * 32 elem * 8hz -> 8192 bits per second. not 1kbps? or you guys quantize latent using FSQ and report latent quantizer's bps?

**Comment by calculating** [comment]
1kbps refers to the information-theoretic bitrate-- the gaussian latents were trained with a kl-regularization objective. Internally we've been able use arithmetic coding to save the latents with a file size at approx the information-theoretic number.
