### ISSUE TITLE
Use which LLM weights?

### ISSUE THREAD

**Issue by SeungdongYoa** [Standard-Intelligence/hertz-dev#31]
Hertz-dev looks fantastic! I’m curious about the weights used in Hertz-LM. Were they initially based on well-known LLMs like GPT-4 or LLaMA, or were they entirely trained from scratch using the 20 million hours of audio data? It seems unlikely that the model was trained solely on audio without leveraging pre-existing LLM weights.

Another question I have is about the architecture. Traditional speech-to-speech AI systems often follow an STT -> LLM -> TTS pipeline, where the AI responds to user input. But it seems like Hertz-dev doesn’t follow this structure. Could you elaborate on the differences and whether the response quality here is comparable to systems that explicitly use LLMs?

Lastly, I’d love to know how well Hertz-dev handles Korean. Has the model been sufficiently trained on Korean data?

Thank you!

**Comment by devanshrpandey** [comment]
the first two questions are explicitly answered [here](https://si.inc/hertz-dev/), let me know at devansh@si.inc if you're still unsure! has been trained on some Korean data but I don't expect it to be great without fine-tuning.
